### ISSUE TITLE
no response after clicking 

### ISSUE THREAD

**Issue by dongtsi** [YU000jp/logseq-plugin-single-journal#5]
点击"之前"按钮后没反应，不显示之前的日志

logseq版本：0.10.8
MAC客户端

**Comment by YU000jp** [comment]
Click on another row.

The line is from Logseq app and should have been hidden by this plugin as it is unnecessary.

TODO:
- [ ] Remove the confusing button

**Comment by dongtsi** [comment]
After watching the demo GIF in the readme, I found that there is no line like "(---display before today)" for me, just Today journal and "Earlier"。 Sometimes, "Earlier" also disappears when I scroll up and down the Today journal.

**Comment by YU000jp** [comment]
It could be a bug, or it could be by design.　There are Journals and journal single pages. Neither is displayed on a journal single page.

**Comment by dongtsi** [comment]
Thx. Is there any native method to control the number of daily pages shown in the Journal view (namely, before "Earlier")?
I remember there could be, but failed to find it now.

**Comment by YU000jp** [comment]
There is no way to customize Journals to open multiple journal. To achieve this, it needs to be implemented as an option in the Logseq core, not as a plugin.
I think such options have the potential to make Logseq a breakthrough, but the developer team doesn't seem to be too keen on adding more small options.

**Comment by YU000jp** [comment]
For example, it should be possible to add an option to this plugin to show 3 days (starting from today) instead of just today, but without any control over those dates. In this case, it would have to be implemented in Logseq core rather than in a plugin, and the developer team doesn't seem to be too fond of small options.

**Comment by sergeybataev** [comment]
same thing in 
logseq 0.10.9 (83)
plugin version: 1.2.0


<details>
  <summary>debug</summary>

  CORS problem I guess

  ```
  	Uncaught (in promise) DOMException: Blocked a frame with origin "lsp://logseq.io" from accessing a cross-origin frame.
	    at zr (lsp://logseq.io/logseq-plugin-single-journal/dist/assets/index-aFl0cje4.js:12:85269)
	    at nt.<anonymous> (lsp://logseq.io/logseq-plugin-single-journal/dist/assets/index-aFl0cje4.js:12:84998)
	    at O.emit (lsp://logseq.io/logseq-plugin-single-journal/dist/assets/index-aFl0cje4.js:3:1788)
	    at #lspmsg# (lsp://logseq.io/logseq-plugin-single-journal/dist/assets/index-aFl0cje4.js:12:12929)
	    at lsp://logseq.io/logseq-plugin-single-journal/dist/assets/index-aFl0cje4.js:12:7777
	zr @ index-aFl0cje4.js:12
	(anonymous) @ index-aFl0cje4.js:12
	O.emit @ index-aFl0cje4.js:3
	#lspmsg# @ index-aFl0cje4.js:12
	(anonymous) @ index-aFl0cje4.js:12
  ```

</details>

**Comment by YU000jp** [comment]
It was the right chase!
